name: Publish Docker image

on: push

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: openvpn

jobs:
  test:
    name: Push Docker image to Github Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Docker buildx 
        uses: docker/setup-buildx-action@v2.0.0

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.0.1
        with:
          images: ${{ github.actor }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable=true

      - name: Build and push Docker image
        uses: docker/build-push-action@v3.0.0
        with:
          context: .
          push: false
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6,linux/386
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      
      - name: Test that the image is correctly built
        run: |
          docker inspect ${{ steps.meta.outputs.tags }}
          docker run --rm ${{ steps.meta.outputs.tags }} openvpn --version
          docker run --rm ${{ steps.meta.outputs.tags }} openssl --version

      - name: Test the image
        run: |
          git clone https://github.com/docker-library/official-images.git official-images
          official-images/test/run.sh ${{ steps.meta.outputs.tags }}
          test/run.sh ${{ steps.meta.outputs.tags }}
